<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PurchaseDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('purchase_details')->delete();
        
        \DB::table('purchase_details')->insert(array (
            0 => 
            array (
                'purchase_details_id' => 35,
                'purchase_id' => 41,
                'product_id' => 29,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1,2,3,4',
                'color_id' => '1,2,3,4',
                'quantity' => 50.0,
                'purchase_price' => 95002.0,
                'sales_price' => 99999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            1 => 
            array (
                'purchase_details_id' => 36,
                'purchase_id' => 42,
                'product_id' => 30,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 51301.0,
                'sales_price' => 53999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            2 => 
            array (
                'purchase_details_id' => 37,
                'purchase_id' => 43,
                'product_id' => 32,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 38000.0,
                'sales_price' => 39999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            3 => 
            array (
                'purchase_details_id' => 38,
                'purchase_id' => 44,
                'product_id' => 31,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1,2,3,4',
                'quantity' => 50.0,
                'purchase_price' => 40850.0,
                'sales_price' => 42999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            4 => 
            array (
                'purchase_details_id' => 39,
                'purchase_id' => 45,
                'product_id' => 33,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 28500.0,
                'sales_price' => 29999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 140,
                'cash_benefit' => 280.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            5 => 
            array (
                'purchase_details_id' => 40,
                'purchase_id' => 46,
                'product_id' => 34,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 28500.0,
                'sales_price' => 29999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            6 => 
            array (
                'purchase_details_id' => 41,
                'purchase_id' => 47,
                'product_id' => 35,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 21521.0,
                'sales_price' => 22499.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            7 => 
            array (
                'purchase_details_id' => 42,
                'purchase_id' => 48,
                'product_id' => 36,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 22956.0,
                'sales_price' => 23999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            8 => 
            array (
                'purchase_details_id' => 43,
                'purchase_id' => 49,
                'product_id' => 37,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 21521.0,
                'sales_price' => 22499.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            9 => 
            array (
                'purchase_details_id' => 44,
                'purchase_id' => 50,
                'product_id' => 38,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 20565.0,
                'sales_price' => 21499.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            10 => 
            array (
                'purchase_details_id' => 45,
                'purchase_id' => 51,
                'product_id' => 39,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 19704.0,
                'sales_price' => 20599.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            11 => 
            array (
                'purchase_details_id' => 46,
                'purchase_id' => 52,
                'product_id' => 40,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 32300.0,
                'sales_price' => 33999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            12 => 
            array (
                'purchase_details_id' => 47,
                'purchase_id' => 53,
                'product_id' => 41,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 29450.0,
                'sales_price' => 30999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 150,
                'cash_benefit' => 300.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            13 => 
            array (
                'purchase_details_id' => 48,
                'purchase_id' => 54,
                'product_id' => 42,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 19130.0,
                'sales_price' => 19999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            14 => 
            array (
                'purchase_details_id' => 49,
                'purchase_id' => 55,
                'product_id' => 43,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => '1',
                'color_id' => '1',
                'quantity' => 50.0,
                'purchase_price' => 16260.0,
                'sales_price' => 16999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => 1,
            ),
            15 => 
            array (
                'purchase_details_id' => 55,
                'purchase_id' => 61,
                'product_id' => 50,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 10490.0,
                'sales_price' => 10990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 40,
                'cash_benefit' => 80.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            16 => 
            array (
                'purchase_details_id' => 61,
                'purchase_id' => 75,
                'product_id' => 51,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 11910.0,
                'sales_price' => 12490.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 50,
                'cash_benefit' => 100.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            17 => 
            array (
                'purchase_details_id' => 62,
                'purchase_id' => 76,
                'product_id' => 51,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 11910.0,
                'sales_price' => 12490.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 50,
                'cash_benefit' => 100.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            18 => 
            array (
                'purchase_details_id' => 63,
                'purchase_id' => 77,
                'product_id' => 52,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 12370.0,
                'sales_price' => 12990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 50,
                'cash_benefit' => 100.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            19 => 
            array (
                'purchase_details_id' => 64,
                'purchase_id' => 78,
                'product_id' => 53,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 13320.0,
                'sales_price' => 13990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 50,
                'cash_benefit' => 100.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            20 => 
            array (
                'purchase_details_id' => 65,
                'purchase_id' => 79,
                'product_id' => 54,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 13670.0,
                'sales_price' => 14490.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            21 => 
            array (
                'purchase_details_id' => 66,
                'purchase_id' => 80,
                'product_id' => 55,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 15630.0,
                'sales_price' => 16490.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            22 => 
            array (
                'purchase_details_id' => 67,
                'purchase_id' => 81,
                'product_id' => 56,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 17130.0,
                'sales_price' => 17999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            23 => 
            array (
                'purchase_details_id' => 68,
                'purchase_id' => 82,
                'product_id' => 57,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 18070.0,
                'sales_price' => 18990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 80,
                'cash_benefit' => 160.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            24 => 
            array (
                'purchase_details_id' => 69,
                'purchase_id' => 83,
                'product_id' => 59,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 19069.0,
                'sales_price' => 19999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 80,
                'cash_benefit' => 160.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            25 => 
            array (
                'purchase_details_id' => 70,
                'purchase_id' => 84,
                'product_id' => 60,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 22399.0,
                'sales_price' => 23499.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            26 => 
            array (
                'purchase_details_id' => 71,
                'purchase_id' => 85,
                'product_id' => 61,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 20749.0,
                'sales_price' => 21999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 110,
                'cash_benefit' => 220.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            27 => 
            array (
                'purchase_details_id' => 72,
                'purchase_id' => 86,
                'product_id' => 62,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 24390.0,
                'sales_price' => 25990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 150,
                'cash_benefit' => 300.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            28 => 
            array (
                'purchase_details_id' => 73,
                'purchase_id' => 87,
                'product_id' => 63,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 25399.0,
                'sales_price' => 26999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 150,
                'cash_benefit' => 300.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            29 => 
            array (
                'purchase_details_id' => 74,
                'purchase_id' => 88,
                'product_id' => 64,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 29790.0,
                'sales_price' => 31990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 210,
                'cash_benefit' => 420.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            30 => 
            array (
                'purchase_details_id' => 75,
                'purchase_id' => 89,
                'product_id' => 65,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 37190.0,
                'sales_price' => 39990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 270,
                'cash_benefit' => 540.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            31 => 
            array (
                'purchase_details_id' => 76,
                'purchase_id' => 90,
                'product_id' => 66,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 32990.0,
                'sales_price' => 34990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 190,
                'cash_benefit' => 380.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            32 => 
            array (
                'purchase_details_id' => 77,
                'purchase_id' => 91,
                'product_id' => 67,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 39990.0,
                'sales_price' => 42990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 290,
                'cash_benefit' => 580.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            33 => 
            array (
                'purchase_details_id' => 78,
                'purchase_id' => 92,
                'product_id' => 58,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 19440.0,
                'sales_price' => 20490.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 90,
                'cash_benefit' => 180.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            34 => 
            array (
                'purchase_details_id' => 79,
                'purchase_id' => 93,
                'product_id' => 68,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 13290.0,
                'sales_price' => 13990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 60,
                'cash_benefit' => 120.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            35 => 
            array (
                'purchase_details_id' => 80,
                'purchase_id' => 94,
                'product_id' => 69,
                'brand_id' => 11,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 990.0,
                'sales_price' => 1190.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 10,
                'cash_benefit' => 20.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            36 => 
            array (
                'purchase_details_id' => 81,
                'purchase_id' => 95,
                'product_id' => 70,
                'brand_id' => 11,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 1770.0,
                'sales_price' => 2150.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 30,
                'cash_benefit' => 60.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            37 => 
            array (
                'purchase_details_id' => 82,
                'purchase_id' => 96,
                'product_id' => 71,
                'brand_id' => 11,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 870.0,
                'sales_price' => 999.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 5,
                'cash_benefit' => 10.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            38 => 
            array (
                'purchase_details_id' => 83,
                'purchase_id' => 97,
                'product_id' => 74,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 1030.0,
                'sales_price' => 1199.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 9,
                'cash_benefit' => 18.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            39 => 
            array (
                'purchase_details_id' => 84,
                'purchase_id' => 98,
                'product_id' => 75,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 3790.0,
                'sales_price' => 4450.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 50,
                'cash_benefit' => 100.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            40 => 
            array (
                'purchase_details_id' => 85,
                'purchase_id' => 99,
                'product_id' => 76,
                'brand_id' => 12,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 555.0,
                'sales_price' => 650.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 2,
                'cash_benefit' => 4.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            41 => 
            array (
                'purchase_details_id' => 86,
                'purchase_id' => 100,
                'product_id' => 77,
                'brand_id' => 6,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 11350.0,
                'sales_price' => 12990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 150,
                'cash_benefit' => 300.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            42 => 
            array (
                'purchase_details_id' => 87,
                'purchase_id' => 101,
                'product_id' => 78,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 18200.0,
                'sales_price' => 20890.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 260,
                'cash_benefit' => 520.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            43 => 
            array (
                'purchase_details_id' => 88,
                'purchase_id' => 102,
                'product_id' => 79,
                'brand_id' => 1,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 2400.0,
                'sales_price' => 2750.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 30,
                'cash_benefit' => 60.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            44 => 
            array (
                'purchase_details_id' => 89,
                'purchase_id' => 103,
                'product_id' => 72,
                'brand_id' => 13,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 1870.0,
                'sales_price' => 2190.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 20,
                'cash_benefit' => 40.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            45 => 
            array (
                'purchase_details_id' => 90,
                'purchase_id' => 104,
                'product_id' => 73,
                'brand_id' => 13,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 770.0,
                'sales_price' => 890.0,
                'courier_cost' => 25,
                'transport_cost' => 25,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 4,
                'cash_benefit' => 8.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            46 => 
            array (
                'purchase_details_id' => 91,
                'purchase_id' => 105,
                'product_id' => 80,
                'brand_id' => 14,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 1045.0,
                'sales_price' => 1350.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 20,
                'cash_benefit' => 40.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            47 => 
            array (
                'purchase_details_id' => 92,
                'purchase_id' => 106,
                'product_id' => 81,
                'brand_id' => 14,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 275.0,
                'sales_price' => 360.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 1,
                'cash_benefit' => 2.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            48 => 
            array (
                'purchase_details_id' => 93,
                'purchase_id' => 107,
                'product_id' => 82,
                'brand_id' => 14,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 1220.0,
                'sales_price' => 1550.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 20,
                'cash_benefit' => 40.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            49 => 
            array (
                'purchase_details_id' => 94,
                'purchase_id' => 108,
                'product_id' => 83,
                'brand_id' => 3,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 2050.0,
                'sales_price' => 2390.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 20,
                'cash_benefit' => 40.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            50 => 
            array (
                'purchase_details_id' => 95,
                'purchase_id' => 109,
                'product_id' => 84,
                'brand_id' => 15,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 4370.0,
                'sales_price' => 4990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 50,
                'cash_benefit' => 100.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            51 => 
            array (
                'purchase_details_id' => 96,
                'purchase_id' => 110,
                'product_id' => 85,
                'brand_id' => 2,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 5150.0,
                'sales_price' => 5990.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            52 => 
            array (
                'purchase_details_id' => 97,
                'purchase_id' => 111,
                'product_id' => 86,
                'brand_id' => 11,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 2650.0,
                'sales_price' => 3050.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 30,
                'cash_benefit' => 60.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            53 => 
            array (
                'purchase_details_id' => 98,
                'purchase_id' => 112,
                'product_id' => 87,
                'brand_id' => 11,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 25.0,
                'purchase_price' => 5720.0,
                'sales_price' => 6590.0,
                'courier_cost' => 0,
                'transport_cost' => 0,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            54 => 
            array (
                'purchase_details_id' => 99,
                'purchase_id' => 113,
                'product_id' => 88,
                'brand_id' => 16,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 14.0,
                'purchase_price' => 184.0,
                'sales_price' => 500.0,
                'courier_cost' => 200,
                'transport_cost' => 50,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 20,
                'cash_benefit' => 40.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            55 => 
            array (
                'purchase_details_id' => 100,
                'purchase_id' => 114,
                'product_id' => 104,
                'brand_id' => 16,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 14.0,
                'purchase_price' => 184.0,
                'sales_price' => 500.0,
                'courier_cost' => 200,
                'transport_cost' => 50,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 20,
                'cash_benefit' => 40.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            56 => 
            array (
                'purchase_details_id' => 101,
                'purchase_id' => 115,
                'product_id' => 90,
                'brand_id' => 19,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 9.0,
                'purchase_price' => 475.0,
                'sales_price' => 1280.0,
                'courier_cost' => 85,
                'transport_cost' => 25,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            57 => 
            array (
                'purchase_details_id' => 102,
                'purchase_id' => 116,
                'product_id' => 92,
                'brand_id' => 22,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 8.0,
                'purchase_price' => 475.0,
                'sales_price' => 1280.0,
                'courier_cost' => 85,
                'transport_cost' => 25,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            58 => 
            array (
                'purchase_details_id' => 103,
                'purchase_id' => 117,
                'product_id' => 91,
                'brand_id' => 21,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 6.0,
                'purchase_price' => 520.0,
                'sales_price' => 1280.0,
                'courier_cost' => 250,
                'transport_cost' => 50,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 60,
                'cash_benefit' => 120.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            59 => 
            array (
                'purchase_details_id' => 104,
                'purchase_id' => 118,
                'product_id' => 89,
                'brand_id' => 20,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 7.0,
                'purchase_price' => 500.0,
                'sales_price' => 1280.0,
                'courier_cost' => 200,
                'transport_cost' => 50,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            60 => 
            array (
                'purchase_details_id' => 105,
                'purchase_id' => 119,
                'product_id' => 89,
                'brand_id' => 20,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 8.0,
                'purchase_price' => 500.0,
                'sales_price' => 1280.0,
                'courier_cost' => 200,
                'transport_cost' => 50,
                'discount' => 0.0,
                'bonus_point' => 0,
                'point_benefit' => 70,
                'cash_benefit' => 140.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
            61 => 
            array (
                'purchase_details_id' => 106,
                'purchase_id' => 120,
                'product_id' => 105,
                'brand_id' => 13,
                'unit_id' => 5,
                'size_id' => NULL,
                'color_id' => NULL,
                'quantity' => 1000.0,
                'purchase_price' => 200.0,
                'sales_price' => 1200.0,
                'courier_cost' => 150,
                'transport_cost' => 50,
                'discount' => 0.0,
                'bonus_point' => 10,
                'point_benefit' => 100,
                'cash_benefit' => 200.0,
                'total_purchase_price' => NULL,
                'is_verified' => NULL,
            ),
        ));
        
        
    }
}